### ISSUE TITLE
Does not compile on FreeBSD 13.0-RELEASE-p4

### ISSUE THREAD

**Issue by devosalain** [Akuli/curses-minesweeper#1]
zig build ends with error:
zig build                                                                                 0
./build.zig:15:45: error: array literal requires address-of operator to coerce to slice type '[][]const u8'
    const valgrind_cmd = b.addSystemCommand([][]const u8{"valgrind"});
                                            ^
./build.zig:15:58: note: referenced here
    const valgrind_cmd = b.addSystemCommand([][]const u8{"valgrind"});
                                                         ^
HOST:x: /home/x/Dirs/Src/Nim/curses-minesweeper >

**Comment by Akuli** [comment]
What does `zig --version` say?

**Comment by Akuli** [comment]
Actually, `zig version`

**Comment by Akuli** [comment]
It should now work with Zig 0.8.1.
