### PR TITLE
Upgrade to Zig 0.8.1

### LINKED ISSUE #1: Does not compile on FreeBSD 13.0-RELEASE-p4
zig build ends with error:
zig build                                                                                 0
./build.zig:15:45: error: array literal requires address-of operator to coerce to slice type '[][]const u8'
    const valgrind_cmd = b.addSystemCommand([][]const u8{"valgrind"});
                                            ^
./build.zig:15:58: note: referenced here
    const valgrind_cmd = b.addSystemCommand([][]const u8{"valgrind"});
                                                         ^
HOST:x: /home/x/Dirs/Src/Nim/curses-minesweeper >

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #1

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -14,25 +14,21 @@ like this:
     $ git submodule init
     $ git submodule update
 
-Then [download zig](https://ziglang.org/download/). At the time of writing this,
-Zig 0.4 hasn't been released yet, so use it if it's listed on the download page
-or use the newest possible zig if it isn't. Download the correct binary (for
-example, `zig-linux-x86_64-something.tar.xz` for 64-bit linux) and move it to
+Then [download zig 0.8.1](https://ziglang.org/download/) and move it to
 the `curses-minesweeper` directory. Then run this:
```
Comment (Akuli) [inline README.md]:
```suggestion
the `curses-minesweeper` directory, and run this:
```

File: src/argparser.zig [hunk 2]
```diff
@@ -33,75 +20,62 @@ fn parseSize(str: []const u8, width: *u8, height: *u8) !void {
...
-    return switch (param.id) {
-        'h' => "show this help and exit",
-        's' => "size of the minesweeper, e.g. 15x10",
-        'n' => "number of mines to add to the game",
-        'a' => "use only ASCII characters",
-        'c' => "don't use colors",
-        else => unreachable,
+pub fn parse(allocator: *std.mem.Allocator) !Args {
+    const params = comptime [_]clap.Param(clap.Help) {
+        clap.parseParam("-h, --help                 Display this help and exit.") catch unreachable,
```
Comment (Akuli) [inline src/argparser.zig]:
```suggestion
        clap.parseParam("-h, --help                 Display this help and exit") catch unreachable,
```

File: src/argparser.zig [hunk 3]
```diff
@@ -33,75 +20,62 @@ fn parseSize(str: []const u8, width: *u8, height: *u8) !void {
...
+        result.nmines = try std.fmt.parseUnsigned(u8, mineCount, 10);
+    }
+    if (args.flag("--ascii-only")) {
+        result.characters = cursesui.ascii_characters;
+    }
+    if (args.flag("--no-colors")) {
+        result.color = false;
     }
 
     // must be at the end because --size and --mine-count can be in any order
```
Comment (Akuli) [inline src/argparser.zig]:
```suggestion
```
